### ISSUE TITLE
range(10) wrong role assignment

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#100]
If you extract UAST for `range(10)` you have next tree:
```
line#   token       Roles

        ||          FILE                                                                                                     
1       ||          ┣ EXPRESSION                                                                                             
1       ||          ┃ ┣ FUNCTION, CALLEE, EXPRESSION                                                                         
1       |10|        ┃ ┃ ┣ EXPRESSION, FUNCTION, DECLARATION, ARGUMENT, NAME, IDENTIFIER, CALLEE, ARGUMENT, NOOP
1       |range|     ┗ ┗ ┗ CALLEE, POSITIONAL, IDENTIFIER, EXPRESSION         
```

What I expect to see is:

```
line#   token       Roles

        ||          FILE                                                                                                     
1       ||          ┣ EXPRESSION                                                                                             
1       ||          ┃ ┣ FUNCTION, CALLEE, EXPRESSION                                                                         
1       |10|        ┃ ┃ ┣ NUMBER, EXPRESSION, ARGUMENT, NAME, IDENTIFIER, ARGUMENT, POSITIONAL, VALUE
1       |range|     ┗ ┗ ┗ CALLEE, IDENTIFIER 
```

not sure about `EXPRESSION` role. It is too common.

Also, I have another experiment and find out that if you parse just `10` you have:
```
  ||   FILE                        
1 ||   ┣ EXPRESSION                
1 |10| ┗ ┗ BYTE, REGEXP, EXPRESSION
```
What I expect to see is:

```
  ||   FILE                        
1 ||   ┣ EXPRESSION                
1 |10| ┗ ┗ NUMBER, EXPRESSION, VALUE
```

BTW, what about `MODULE` role? Each file in python is considered as the module, or I am wrong?

**Comment by juanjux** [comment]
Was because of the desync between the SDK numeric roles, fixed in the latest version that should be incorporated in the python-driver 1.0.3 image.

In this case, there is a bug where the "10" also have the roles `Function, Declaration, Call` that should not be there (`Call` because the parent node has already it). The fix will be in the next version.

The role `Module` is a product of the decomposition of the previous `VisibleFromModule` and thus originally applied to the visibility/writability modifiers (like "global" in Python), but since now it makes sense to apply it to the root node in Python too, I've changed this and the fix will be in the next version.

**Comment by zurk** [comment]
ok now it is better 
```
#  Token  Internal Role  Roles Tree                     
                                                        
   ||     Module         FILE                           
1  ||     Expr           ┣ EXPRESSION                   
1  |10|   Num            ┗ ┗ LITERAL, NUMBER, EXPRESSION
```

But I dont see `VALUE` role. From doc:
```
    // Value is an expression that cannot be evaluated any further.
    Value
```
So, It fits.

**Comment by juanjux** [comment]
`Value` AFAIK is for key/value pairs (like in maps, named arguments, etc), comes from the decomposition of the old roles:

- FunctionDeclarationArgumentDefaultValue
- CallNamedArgumentValue
- MapValue
...etc.

 the description in the UAST should be improved. Anyway there isn't any way in the native AST to identify "an expression that cannot be evaluated any further"; you have literals, or identifiers but not that.
