### ISSUE TITLE
What the difference between IDENTIFIER and NAME Roles for python?

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#108]
The [documentation](https://godoc.org/github.com/bblfsh/sdk/uast#Role) says:
```
// Identifier is any form of identifier, used for variable names, functions, packages, etc.
    Identifier
...
// Name is an identifier used to reference a value.
    Name
```

But in Python all identifiers are references.
So, what the difference between this two roles in Python?
If there is no difference we should add NAME role to each IDENTIFIER Node.

**Comment by juanjux** [comment]
Maybe the description in the UAST is not well worded. `Reference` is not in this case a reference in the sense of "reference vs value" types, but a reference to an accessor, like a named argument in a function:

Example:

```
def foo(a, b, c):
    d = 4
foo(1, 2, c=3)
```

Here, `a`, `b` and `c` are both `Identifier` and `Name` but `d` is only an `Identifier`.

**Comment by zurk** [comment]
Ok, I think it is better to clarify in the documentation.
