### ISSUE TITLE
PRIMITIVE role meaning for Python

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#109]
The [documentation](https://godoc.org/github.com/bblfsh/sdk/uast#Role) says:
```
    // Primitive is a language builtin.
    Primitive
```

Python has a lot of built-in names, but since I can override any built-in function it is not possible to say if this name built-in or not. 

Can you please clarify `Primitive` role meaning for Python?

**Comment by juanjux** [comment]
I could be wrong, but I think [Primitive](https://en.wikipedia.org/wiki/Primitive_data_type) refers to a language builtin type (like integer, strings, et cetera, that is, not user defined types like classes) not keywords.

The native AST itself doesn't mark if an identifier is built it or not but we could certainly add the Primitive role to Num, String, Byte, Boolean and None nodes.

**Comment by zurk** [comment]
Ok, 
So there are two points:
1. Extend the documentation string to be more specific about the role.
2. Add Primitive role to nodes, where it is necessary. 
The last one can be tricky because python has many built-in types (https://docs.python.org/3/library/stdtypes.html), and somewhere we can not check it. So, good idea to specify which types are Primitive for Python. 
For example, as you said
> Num, String, Byte, Boolean and None

**Comment by juanjux** [comment]
Note that I edited my message to add more. 

I'm currently adding the primitive role to: Num (which include all numerical types), String, Byte, Boolean, Set, Dict, List and Tuple.

**Comment by juanjux** [comment]
Fixed by #110.
