### ISSUE TITLE
Nodes without any roles.

### ISSUE THREAD

**Issue by fineguy** [bblfsh/python-driver#114]
I wrote a small tool for collecting statistics for number of nodes w.r.t. number of node roles in UASTs. It turned out that for my dataset there're some cases when no roles are assigned to a UAST node.

Repositories: `/storage/timofei/repos`
Extracted UASTs: `/storage/timofei/uasts`
Collected statistics: [uasts_stat.txt](https://github.com/bblfsh/python-driver/files/1345149/uasts_stat.txt)
List of suspicious UASTs (csv file with columns: path to UAST, total number of nodes, number of nodes without roles): [uasts_susp.txt](https://github.com/bblfsh/python-driver/files/1345148/uasts_susp.txt)

**Comment by mcuadros** [comment]
Version of driver and server?

**Comment by fineguy** [comment]
I'm using v1.0.2 driver and v.1.0.0 server (As far as I can tell from `docker inspect bblfsh/server`)

**Comment by fineguy** [comment]
Wow, my bad, I was actually using v0.2.1 driver: [https://github.com/src-d/ast2vec/blob/develop/requirements.txt](https://github.com/src-d/ast2vec/blob/develop/requirements.txt)

**Comment by fineguy** [comment]
And the issue is actually for [https://github.com/bblfsh/client-python](https://github.com/bblfsh/client-python)
