### ISSUE TITLE
Evaluate parso as an alternative/complementary native AST generator

### ISSUE THREAD

**Issue by juanjux** [bblfsh/python-driver#127]
This totally flew under my radar when I evaluated jedi as a parser I only checked jedi's API but not the implementation (:-1: for me).

https://parso.readthedocs.io/en/latest/

From a quick evaluation, I saw advantages and negatives over the native AST module:

**Advantages:**

- Support for [error retrieval](https://parso.readthedocs.io/en/latest/docs/usage.html#error-retrieval).
- More straightforward inheritance-based API that makes easy to reason about the kind of a node.
- Removes some of the WTF's of the native driver like the structure of default/keyword parameters. 
- Support comments and whitespace, trough seems to be worse that our implemented solution (group all comment groups on node, properties, no positions for comments, etc).
- Much better node locations, including ending positions, which would simplify the native parser quite a bit.

**Disadvantages:**

- Pure Python, so probably a lot slower than the (native) default `ast` module.
- Version 0.0.1 with the promise that the API will change.
- A lot of nodes lose information typed in the native AST (for example, there is not "AssignExpr" type, they're just "expr_stmt", no list, set or dict nodes, no diferentiation among comprehension types...).
- Some nodes doesn't seem to have all the information compared to the native ones (e. g. "FormattedValue", "JoinedStr")
- Some nodes require to call for special methods on the node class to get some of the children, which complicates somewhat the visitor.
- Tokens are a lot more distributed on different properties trough this shouldn't be a problem with the SpecificTokens SDK feature.

Probably a good middle point would be to use it to complete the native AST to provide more positions 
 (and more reliable) for all nodes where the tokenizer can't provide one (like nodes that doesn't even have a line number). It could also be used as a fallback when a broken source code doens't get parsed by the native AST, but that would be more complicated since the structure of the  generate tree would be different (but still, could be used to provide better errors).

**Comment by abeaumont** [comment]
I think this could be closed now.
