### ISSUE TITLE
Docker image of the python driver doesn't work in macOS

### ISSUE THREAD

**Issue by abeaumont** [bblfsh/python-driver#128]
Following the procedure indicated at https://github.com/bblfsh/documentation/issues/102, after the permission fix at https://github.com/bblfsh/bblfshd/pull/127, the following problem remains:

```
$ docker exec -it bblfshd bblfshctl driver install --all
Installing python driver language from "docker://bblfsh/python-driver:latest"... Error
Error, link /var/lib/bblfshd/tmp/image823718068/usr/share/terminfo/2/2621 /var/lib/bblfshd/tmp/image823718068/usr/share/terminfo/2/2621a: file exists
Installing java driver language from "docker://bblfsh/java-driver:latest"... Done
```

Looking at the image contents, the following can be seen:

```bash
# ls -l /var/lib/bblfshd/images/1065e9aa41993936dc7efddee542c482ec5fcb053c5966207e5641d315d1d2b4/43770460b97dae4dd93bf8f9e9dcc9f06349533c10fd6a1154afde0021b8a189/usr/share/terminfo/2
total 16
-rw-r--r-- 8 root root 622 Oct 26 12:13 2621
-rw-r--r-- 8 root root 622 Oct 26 12:13 2621-wl
-rw-r--r-- 8 root root 622 Oct 26 12:13 2621A
-rw-r--r-- 8 root root 622 Oct 26 12:13 2621a
#
```

So it seems that this package, which is a depedency of the python package in alpine, contains files that only have case changes, while macOS filesystem is case-insensitive, which is probably causing the problem.

**Comment by abeaumont** [comment]
As indicated [here](https://github.com/docker/for-mac/issues/320#issuecomment-315324629), a workaround may be to create and use a case-sensitive file system in this case, which doesn't seem the easiest thing to do. We could either document this or drop macOS support for now, what do you think @juanjux @mcuadros ?

**Comment by juanjux** [comment]
Mmmm, we could install Python from the official binary packages or pyenv instead of Alpine's packages. I'll try it on thursday to see if we have the same problem.

**Comment by abeaumont** [comment]
The problem is not with python itself but a dependency. Anyway, I don't see why that would fix the problem. The duplicated files could also just be removed, but I don't think that's the best option either.

**Comment by juanjux** [comment]
The previous version of Alpine didn't have Python 3.6 so we installed from the Python binary package and it worked without installing any other dependency... but even it that work, there could be other case-duplicated files, so probably it's less painful to drop macOS support until docker/for-mac/issues/320 is fixed.

**Comment by juanjux** [comment]
cc @mcuadros

**Comment by zurk** [comment]
Just find this issue by myself, do we have any solution or decision here?
@mcuadros @abeaumont ?

**Comment by mcuadros** [comment]
@juanjux please answer to this, with the solution we agreed.

**Comment by juanjux** [comment]
@zurk from: https://doc.bblf.sh/user/getting-started.html#running-with-docker-recommended

On macOS, remove the parameter -v /var/lib/bblfshd:/var/lib/bblfshd since the default case insensitive filesystem could conflict with the internal drivers' case sensitive one. In that case remember that since this directory will then be ephemeral, you'll need to reinstall the drivers after creating a new server container.
