### ISSUE TITLE
empty list of roles

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#132]
Hi,
I figured out that in some cases bblfsh returns empty list of roles.
I checked some cases - and found 3 options -
* empty file (like `__init__.py`)
* file with unexpected encodings
* something suspicious ([ex](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_common.py) - bblfsh tells that `time="2017-11-06T06:49:27Z" level=error msg="request processed content 25441 bytes, status Fatal" elapsed=71.836012ms language=python`) - I can't find wrong encoding here

Can you confirm that this behavior is correct?
And what is the problem with last case?

**Comment by juanjux** [comment]
A node without roles would have the `Unannotated` role (it's hardcoded in the SDK for new nodes), is that the case? 

An empty file would return an empty UAST - this is done in the server, the driver doesn't even get the request in that case. Is this not happening? (It happened in my test).

The file in the third point parses well for me using the Python client.

Could you provide gist pastes of the output you're getting in the three cases?

**Comment by abeaumont** [comment]
Closing for now, reopen if still applies.
