### ISSUE TITLE
Comments are not merged

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/python-driver#148]
Successive "#" comments are not merged into a single node. Besides, there are spurious "\n" comments in between.

**Comment by juanjux** [comment]
I don't think they should be merged, for the reason explained in the go-driver issue. 

I guess that the newlines are the ones that have the internal type NoopLine. I'm seeing that they're wrongly tagged as Comment (should be Noop+Whitespace). I'll fix that.

**Comment by juanjux** [comment]
The \n nodes were removed some time ago.
