### ISSUE TITLE
Support Cython

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/python-driver#150]
Enry sometimes detects Cython files as Python and they are feeded to the Python driver, and then fail.

For sure not an important feature request.

**Comment by juanjux** [comment]
It's problematic because the native AST we use just doesn't recognize Cython. An easy (but nor very good) fix would be to remove the cdefs and types on Cython files before passing them to Python, since,  if I remember correctly,  there isn't much more to it over normal Python.

**Comment by smola** [comment]
By the way, there is a PR at github/linguist proposing Cython detection as something separated from Python: https://github.com/github/linguist/pull/4181

**Comment by juanjux** [comment]
I think we should close this, Cython is a different language after all and the problem of separating both is on linguist/enry, what do you think @vmarkovtsev?
