### ISSUE TITLE
[feature request] Add support to query supported languages (with installed drivers)

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#155]
Similar to https://github.com/bblfsh/client-scala/issues/68 it is really useful to have this feature in Python client.
Now we (ML team) have a hardcoded list of languages:  https://github.com/src-d/ml/blob/master/sourced/ml/cmd_entries/args.py#L36-L40 and we should update it each time.

**Comment by dennwc** [comment]
This is a repository of Python _driver_, not the client  :)

**Comment by bzz** [comment]
🤦‍♂️  https://github.com/bblfsh/client-python

**Comment by zurk** [comment]
woops, sorry, it was miss-click.
