### ISSUE TITLE
column out of bounds

### ISSUE THREAD

**Issue by smacker** [bblfsh/python-driver#164]
Most probably introduced by #161 

The latest driver fails on this file:
https://github.com/pallets/itsdangerous/blob/master/itsdangerous.py

full error: `[column out of bounds: 38 [1, 37]]`

older driver parses it without problems (for example it works on http://dashboard.bblf.sh/ )

**Comment by juanjux** [comment]
I'll take a look.

**Comment by juanjux** [comment]
What version are you using? I couldn't reproduce this with `python -m bblfsh -f file` or adding it as an integration tests and running the generation command. I'm using the latest (v2.2.1) version of the driver and `latest` of bblfshd from Docker Hub.

**Comment by smacker** [comment]
```
"python-driver version: v2.2.1 (build: 2018-08-02T18:39:59Z)"
```

bblfshd latest.

Sorry for missleading source! After wget it doesn't fail indeed! But it fails on [my fixture](https://github.com/smacker/bblfsh-benchmark/blob/master/fixtures/large.py). Diff:

```
$ diff itsdangerous.py fixtures/large.py
900c900
<     default_serializer = _CompactJSON
---
>     default_serializer = _CompactJSON
\ No newline at end of file
```

New driver:
```
$ python -m bblfsh -f fixtures/large.py -e 127.0.0.1:9800 > /dev/null
column out of bounds: 38 [1, 37]
```

Old driver:
```
$ python -m bblfsh -f fixtures/large.py -e 127.0.0.1:9432 > /dev/null
(.pyenv) smacker at Maxims-MacBook-Pro in ~/Dev/bblfsh-benchmark on master*
```

**Comment by juanjux** [comment]
Yes, that was it, Vim was being a too good boy and was adding a newline at the end of the file, removing it (`perl -pi -e 'chomp if eof' filename.py`) now I can reproduce the problem.

**Comment by juanjux** [comment]
SDK updated. Drivers will need individual updates to get this fix, I'll update the python-driver now but

**Comment by juanjux** [comment]
v2.2.2 of the Python driver released which should incorporate the fix.
