### ISSUE TITLE
Driver returns twice every inline comment

### ISSUE THREAD

**Issue by dpordomingo** [bblfsh/python-driver#167]
When an inline comment is parsed, it is returned a structure that is different compared to other comments or compared to other drivers:
It is returned a `<SameLineNoopscontaining roleComment>` having `position` and containing a `<NoopSameLine roleComment>` without `position`.

The comment token itself contains a leading `#` character what does not happen for regular python comments.
```python
a = Animal() # line comentary
```

![image](https://user-images.githubusercontent.com/2437584/45689388-1fcd5f00-bb54-11e8-831c-abd4c42f7327.png)

***addendum:***
This issue might be related to these similar ones in other languages drivers:
https://github.com/bblfsh/javascript-driver/issues/36 https://github.com/bblfsh/go-driver/issues/28 https://github.com/bblfsh/java-driver/issues/86

**Comment by juanjux** [comment]
For what I'm seeing, the dashboard is not using Semantic UAST so it's normal that the structure is different among languages.

**Comment by dpordomingo** [comment]
The issue is not (only) about the dashboard but about the response I get from **bblfsh**.

I found the unexpected behavior with `lookout` using the `typos-checker` analyzer when reviewing [this comment](https://github.com/dpordomingo/testing-repo/pull/37/files#r218439862), wrongly placed in a wrong line (because the comment node seems to have no `position` as it also happened in the **dashboard**).

The **bblfsh** I'm runing to get that behaviour is:
```js
{
  server: {
    version: 'bblfsh/bblfshd:v2.5.0'
  },
  drivers: {
    'python': {
      image: 'docker://bblfsh/python-driver:latest'
      version: 'v2.3.0'
      native: 'python:3.6-alpine'
    }
  },
}
```

Should I configure my env in a different way to use **bblfsh** with Semantic UAST?

**Comment by juanjux** [comment]
I was testing this, and could not reproduce with the latest versions - all kinds of comments only appear once. BUT I found another problem: some comments doesn't appear in the UAST output. I'll investigate that.
