### ISSUE TITLE
transform failed: column out of bounds: 29 [1, 25]

### ISSUE THREAD

**Issue by smacker** [bblfsh/python-driver#181]
On file: https://github.com/src-d/or-tools/blob/master/examples/python/word_square.py
Most probably due to this line: https://github.com/src-d/or-tools/blob/master/examples/python/word_square.py#L121

bblfsh 2.11.8-drivers

**Comment by dennwc** [comment]
File is not UTF-8. Won't fix.

**Comment by creachadair** [comment]
> File is not UTF-8. Won't fix.

Agreed as far as the functionality, but can we do something to make the error diagnostic more indicative? E.g., when we get a file can we do a quick check for UTF-8 and if it fails, report an error immediately so that the end user knows what happened?

**Comment by dennwc** [comment]
This happened on bblfshd version that had no check for UTF-8. The new one should return a better error.
