### ISSUE TITLE
IfCondition Role not asigned in some cases

### ISSUE THREAD

**Issue by dpaz** [bblfsh/python-driver#20]
When you have an If which don't have the usual form like a binary expression the role IfCondition dont appear in the UAST, for an input like this:
```
 if True:
	    print(True)
``` 
or
```
if functionCallThatReturnsABoolean(){
           print(True)
}
```
the uast roles that we expect is something like this
```
If{
           IfCondition,
           IfBody
}
```
and we get this
```
If{
           IfBody
           expresion/functionCall
}
```

**Comment by juanjux** [comment]
Confirmed.

Actually the bool literal in "if True:" shows in the UAST but it doesn't have the IfCondition role (only BooleanLiteral) so it's definitely a bug.

**Comment by juanjux** [comment]
Should be fixed by the PR referenced above.
