### ISSUE TITLE
Parsing an empty file produces a fatal error

### ISSUE THREAD

**Issue by juanjux** [bblfsh/python-driver#25]
Sending an empty file to the Python driver produces a fatal error (with by definition stops the driver from processing more requests). This shouldn't be so since empty files are common in Python (__init__.py), it should just produce an error with an empty UAST returned.

**Comment by juanjux** [comment]
Should be fixed by PR #26.

**Comment by bzz** [comment]
Oh, so cool! 🎉 

Just spend few hours of life banding my head on

```
Read kalipo-ir/harvester/__init__.py, 0 bytes	Parsing file:'kalipo-ir/harvester/__init__.py', content:''
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1186147]

goroutine 1 [running]:
github.com/bblfsh/sdk/uast.(*Node).ProtoSize(0x0, 0xc4201e0f90)
```

**Comment by juanjux** [comment]
@bzz the fix has been merged, could you try again with the new version of ~master? Or do you need a new Python driver docker image?
