### ISSUE TITLE
Snippet produces wrong offset

### ISSUE THREAD

**Issue by juanjux** [bblfsh/python-driver#65]
This code:

```python
class Repo2nBOW(Repo2Base):
    @property
    def id2vec(self):
        return self._id2vec
```

Produces and offset of 0 for `_id2vec`.

**Comment by juanjux** [comment]
CC @egorbu

**Comment by juanjux** [comment]
Should be fixed in v0.7.1 (update the client-python too), thanks for the report!

**Comment by zurk** [comment]
Nope, unfortunately not.
I update client, bblfsh server and python driver.

Here is an example.
https://gist.github.com/zurk/a81fa263c2ea64a04a7b7bb96b1fdb40
It does not work correctly with the `end_position.offset` of `FUNCTION_DECLARATION` role (last character missed).

**Comment by juanjux** [comment]
Different problem, the output of the first snippet produced a 0 offset on the last element because of an out of bounds problem caused by decorated functions taking the line number of the decorador as start. 

Please open another issue, in this case the function definition gets the end position of the element with the farthest position  so it looks that in this case the problem is that the function call is getting the position of the last argument.

 Probably could be fixed just adding 1 to the end position of function calls since we don't have any way of getting the end position of the last parenthesis (the Python AST doesn't provide endpositions, we calculate it from the endpositions of tokens, which a parenthesis is not), but that wouldn't help totally correct since the closing parenthesis could be in another line.
