### ISSUE TITLE
There is no simple identifier of module when I import submodule

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#68]
I run this code:
```python
from bblfsh.client import BblfshClient
bc = BblfshClient("0.0.0.0:9432")
res = bc.parse("example.py", language="Python")
print(res)
```
where `example.py` is 
```python
import matplotlib.pyplot
```

Here is full output:
```
uast {
  internal_type: "Module"
  children {
    internal_type: "Import"
    properties {
      key: "internalRole"
      value: "body"
    }
    children {
      internal_type: "Import.names"
      properties {
        key: "promotedPropertyList"
        value: "true"
      }
      children {
        internal_type: "alias"
        properties {
          key: "asname"
          value: "<nil>"
        }
        token: "matplotlib.pyplot"
        start_position {
          line: 1
          col: 1
        }
        roles: IMPORT_PATH
        roles: SIMPLE_IDENTIFIER
      }
      roles: 142
    }
    start_position {
      line: 1
      col: 1
    }
    roles: IMPORT_DECLARATION
    roles: STATEMENT
  }
  start_position {
    line: 1
    col: 1
  }
  roles: FILE
}
```

Why don't I have matplotlib as a simple identifier?
Is it correct?

**Comment by juanjux** [comment]
Look like that's the way the native AST gives the token, it creates a single node for all the path.

**Comment by zurk** [comment]
Ok, then, if I need to understand which modules are imported in this file, I should split it with dot `.`.
I think that it is a common situation when you need to process imports somehow. 
Is it may be better to split it inside driver?

**Comment by juanjux** [comment]
At this point we're trying to avoid creating new nodes from the native AST, just annotating them so at the moment the only solution for this is for the client to do the split.

**Comment by zurk** [comment]
Ok, thank you!
It is not a problem for now, but as we want to build universal system (`ast2vec`) to process all languages, it can be not so simple and beautiful solution. :)

May be some tools will help to solve this problem later. Like `libaust` for example.

For now, I think you can close it if you see fit.

**Comment by juanjux** [comment]
Native AST parsers all have these "WTF"'s and while we could patch the two existing drivers to solve most of them, that doesn't scale to 10, 20 or 100 drivers.

In the future it's my opinion that we'll need to write (or find) some generic parsing system so we won't depend on the native parsers, at least for some languages. But that's is a distant future right now :)

**Comment by juanjux** [comment]
I'll left this open as enhacement so we don't forget it we have some generic solution in the future.

**Comment by abeaumont** [comment]
This is out of scope for a driver. Closing..
