### ISSUE TITLE
CALL Node for len has no CALL_CALLEE child

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#71]
If you get UAST for `len(x)` you will get no `CALL_CALLEE` child in `CALL` Node but the documentation (http://godoc.org/github.com/bblfsh/sdk/uast#Role) says:
```
// Call is any call, whether it is a function, procedure, method or macro.
// In its simplest form, a call will have a single child with a function
// name (CallCallee).
```

So, as I understand any `CALL` should have `CALL_CALLEE` child.

**Comment by zurk** [comment]
It seems that any function does not have `CALL_CALLEE` child.
I run:
```python
res = BblfshClient("0.0.0.0:9432").parse('example.py', language='Python')
print(res)
```
and `example.py` is
```python
def function():
    pass

function()
```

here you can find full UAST: https://gist.github.com/zurk/4764b6a9d04c8ba6bbe8b6385c1d5f60

Also I found that it has two `CALL` nodes. Line [138](https://gist.github.com/zurk/4764b6a9d04c8ba6bbe8b6385c1d5f60#file-uast-L138) and [152](https://gist.github.com/zurk/4764b6a9d04c8ba6bbe8b6385c1d5f60#file-uast-L152).

**Comment by abeaumont** [comment]
Thanks @zurk. I can confirm both bugs. In the future please report a single problem per issue for better tracking.
