### ISSUE TITLE
SIMPLE_IDENTIFIER is not assigned to argument names

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#73]
Hi!
SIMPLE_IDENTIFIER is not assigned when it has to be assigned.
better ex:
```
def some_funct(some_arg):
  pass

some_funct(some_arg=some_val)

some_funct(some_arg=some_arg)

```
Vis:
![selection_009](https://user-images.githubusercontent.com/2606702/29325877-a1450434-81e9-11e7-8d55-bd2746c550b4.png)

PS: and there's some magic when you pass variable with the same name as argument

**Comment by abeaumont** [comment]
Thanks for the report @EgorBu. Please note that you can use GH's markdown syntax highlighting instead of attaching an image of the code. Could you attach the generated UAST instead and indicate which part you think is wrong?

**Comment by juanjux** [comment]
Unfortunately the position in this case is missing in both in the native AST and the tokenizer:

```python
'keywords': [{'arg': 'some_arg',
                    'ast_type': 'keyword',
                    'value': {...}}
                   ],
```

So under current specifications and the decision to not add position workarounds/heuristics to the drivers I have to close.
