### ISSUE TITLE
Decorator for class breaks logic of computation of start position of class name

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/python-driver#74]
Hi,

ex:
```
@register_class
class a:
    pass

```

vis:
![selection_006](https://user-images.githubusercontent.com/2606702/29321875-13282d0a-81dc-11e7-97ec-71648dda8f3d.png)

**Comment by juanjux** [comment]
Yeah, probably we've to add another "special handling" for ClassDef in the driver.

**Comment by abeaumont** [comment]
Depends on https://github.com/bblfsh/sdk/issues/163

**Comment by juanjux** [comment]
Unfortunately the position in this case is wrongly given both in the native AST and the tokenizer.

So under current specifications and the decision to not add position workarounds to the drivers I have to close.
