### ISSUE TITLE
Strange role assignment  in version v0.9.0

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#91]
It is not published in github, but the latest here https://hub.docker.com/r/bblfsh/python-driver/tags/

I will give an example from dashboard:
<img width="659" alt="screen shot 2017-09-18 at 19 12 35" src="https://user-images.githubusercontent.com/516045/30554619-6e153cc4-9ca5-11e7-9aee-33f432be519d.png">
As you can see there are completely strange roles in bblfsh.
If I run version v0.8.2 using `BBLFSH_DRIVER_IMAGES="python=docker://bblfsh/python-driver:v0.8.2"` everything is fine.  

Maybe It is erroneous release...

**Comment by juanjux** [comment]
Version 0.9.0 of the driver uses SDK/UAST version 1, so this is normal, use 0.8.2 that is the last version linking vs SDK v0 or wait for the release of the next server image (probably today).
