### ISSUE TITLE
Identifiers with empty tokens. 

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#94]
I found identifiers with empty tokens.
https://gist.github.com/zurk/8f7dd974347925ae62c31d9441491613

Here you can find my example. 
run `run_me.py` and you get `output` for `example.py`
I think that all identifiers cannot be with empty tokens. 
Or am I wrong?

**Comment by juanjux** [comment]
Almost certainly, they shouldn't have empty tokens.

**Comment by juanjux** [comment]
PS: in this specific case, the error is those nodes having the `Identifier` role since in the Python AST `arguments` (the ones in this example) are "virtual" grouping nodes without textual representation (in this case it serves as common parent to all arguments).

Should be easy to fix.

**Comment by juanjux** [comment]
Fixed by #112, I checked that all nodes with an `IDENTIFIER` token in your provided code have a token.
