### ISSUE TITLE
Duplication of IDENTIFIER role

### ISSUE THREAD

**Issue by zurk** [bblfsh/python-driver#96]
I found it in the output of this example https://gist.github.com/zurk/8f7dd974347925ae62c31d9441491613 for issue https://github.com/bblfsh/python-driver/issues/94.

for `self` token we have role duplication:

`<self>:         ['IDENTIFIER', 'QUALIFIED', 'IDENTIFIER', 'EXPRESSION']`

or for `class1`:
`<class1>:       ['IDENTIFIER', 'QUALIFIED', 'IDENTIFIER', 'EXPRESSION']`

**Comment by juanjux** [comment]
Yes, I think that with the current UAST it will be unavoidable to have some duplicated roles, trough I'm pretty sure most of the current ones can be eliminated. There is a feature request in the SDK to automatically eliminate duplicates (https://github.com/bblfsh/sdk/issues/174) but I don't want to implement it yet precisely to detect these easily avoidable cases.

**Comment by zurk** [comment]
Ok, got it! 
It is not a big problem, so fix it when you are ready.

**Comment by juanjux** [comment]
Fixed by #112.

**Comment by juanjux** [comment]
Fixed by #122.
